title: Ciclo de Formación SiB Colombia
lang: en-US
description: Just another documentation theme compatible with GitHub Pages, based on sphinx_rtd_theme

edit: true

copyright:
  revision: true

addons:
  - github
  - analytics

addons_commit: true

#remote_theme: rundocs/jekyll-rtd-theme
remote_theme: daattali/beautiful-jekyll@4.0.1

# use front matter sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed
