title: Laboratorio de Formaci贸n SiB Colombia
lang: en-US
description: Laboratorio de Formaci贸n para la Gesti贸n, Publicaci贸n y Uso de Datos sobre Biodiversidad 
logo: Formacion/Logo SiB Colombia_ Blanco-12.png


edit: true

copyright:
  revision: true

addons:
  - github
  - analytics

addons_commit: true

remote_theme: rundocs/jekyll-rtd-theme
#remote_theme: daattali/beautiful-jekyll@4.0.1

#Set up code highlight
rougify: github

# use front matter sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed
