title: Laboratorio de Formaci贸n SiB Colombia
lang: es-CO
description: Laboratorio de Formaci贸n para la Gesti贸n, Publicaci贸n y Uso de Datos sobre Biodiversidad 
logo: https://sibcolombia.net/wp-content/uploads/2018/06/logo-sib.svg


edit: true

copyright:
  revision: true

addons:
  - github
  - analytics

addons_commit: true

remote_theme: rundocs/jekyll-rtd-theme
#remote_theme: daattali/beautiful-jekyll@4.0.1

#Set up code highlight
rougify: github

# use front matter sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed
