remote_theme: daattali/beautiful-jekyll@4.0.1

section:
  - page: Introduction
    url: /contexto
    subsection:
      - page: Getting Started
        url: https://github.com/SIB-Colombia/Formacion/blob/master/contexto.md
      - page: Configuration
        url: /intro/config
      - page: Deploying
        url: /intro/deploy
  - page: Advanced Usage
    url: /usage
    subsection:
      - page: Customizing
        url: /usage/customizing
      - page: All Configuration Settings
        url: /usage/settings
      - page: Help and Support
        url: /usage/support
